#%RAML 1.0
title: "Earth"
version: "v1"
protocols:
- "HTTP"
baseUri: "http://127.0.0.1:8888/api/v1"
/login:
  post:
    description: "user can login by account and password"
/register:
  post:
    description: "new user register"
